// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAA504wafsILL3i1ssC0q60MF2jv2ldBGM',
    appId: '1:647974454520:web:a6c639b73098abf442270d',
    messagingSenderId: '647974454520',
    projectId: 'deepseekclonewithvertexai',
    authDomain: 'deepseekclonewithvertexai.firebaseapp.com',
    storageBucket: 'deepseekclonewithvertexai.firebasestorage.app',
    measurementId: 'G-HCVPDBFXRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACV-s1O1fRLcjx3WoE45JsYfCnfat692M',
    appId: '1:647974454520:android:3fb41f60ba506d1142270d',
    messagingSenderId: '647974454520',
    projectId: 'deepseekclonewithvertexai',
    storageBucket: 'deepseekclonewithvertexai.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPZP1eef3dxmsP04pxnI2xav7pOhnDrJo',
    appId: '1:647974454520:ios:51a96de975f09d2742270d',
    messagingSenderId: '647974454520',
    projectId: 'deepseekclonewithvertexai',
    storageBucket: 'deepseekclonewithvertexai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPZP1eef3dxmsP04pxnI2xav7pOhnDrJo',
    appId: '1:647974454520:ios:51a96de975f09d2742270d',
    messagingSenderId: '647974454520',
    projectId: 'deepseekclonewithvertexai',
    storageBucket: 'deepseekclonewithvertexai.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAA504wafsILL3i1ssC0q60MF2jv2ldBGM',
    appId: '1:647974454520:web:c4d1898f279f084742270d',
    messagingSenderId: '647974454520',
    projectId: 'deepseekclonewithvertexai',
    authDomain: 'deepseekclonewithvertexai.firebaseapp.com',
    storageBucket: 'deepseekclonewithvertexai.firebasestorage.app',
    measurementId: 'G-CJ14M1VY8B',
  );
}
